<?php

namespace Database\Seeders;

use App\Models\BetCompany;
use Illuminate\Database\Seeder;

class BetCompaniesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $betcompanies =  [
            ['name' => 'tipobet365'],
            ['name' => 'mobilbahis'],
            ['name' => 'jetbahis'],
            ['name' => 'youwin'],
            ['name' => '1xbet'],
            ['name' => 'bets10'],
            ['name' => 'superbahis'],
            ['name' => 'rexbet'],
            ['name' => 'betboo'],
            ['name' => 'bahigo'],
            ['name' => 'betsat'],
            ['name' => 'superbetin'],
            ['name' => 'betwinner'],
            ['name' => 'mobilbahis'],
            ['name' => 'mobilbahis'],
            ['name' => 'mobilbahis'],
            ['name' => 'mobilbahis'],
            ['name' => 'mobilbahis'],

            ['name' => 'supertotobet'],
            ['name' => 'betmatik'],
            ['name' => 'betvole'],
            ['name' => 'pusulabet'],
            ['name' => 'bahiscom'],
            ['name' => 'betebet'],
            ['name' => 'betsoo'],
            ['name' => 'ilbet'],
            ['name' => 'neyinee'],
            ['name' => 'vdcasino'],
            ['name' => 'onwin'],
            ['name' => 'oslobet'],
            ['name' => 'betpark'],
            ['name' => 'vegabet'],
            ['name' => 'kolaybet'],
            ['name' => 'betist'],
            ['name' => 'aspercasino'],
            ['name' => 'sekabet'],
            ['name' => 'sahabet'],
            ['name' => 'betgram'],
            ['name' => 'mariobet'],
            ['name' => 'bettilt'],
            ['name' => 'elitbahis'],
            ['name' => 'paribahis'],
            ['name' => 'gobahis'],
            ['name' => 'maksibet'],
            ['name' => 'pinbahis'],
            ['name' => 'onbahis'],
            ['name' => 'asyabahis'],
            ['name' => 'piabet'],
            ['name' => 'arzbet'],
            ['name' => 'milanobet'],
            ['name' => 'betlike'],
            ['name' => 'liderbahis'],
            ['name' => 'betticket'],
            ['name' => 'venusbet'],
            ['name' => 'elexbet'],
            ['name' => 'oleybet'],
            ['name' => 'kingbetting'],
            ['name' => 'garabet'],
            ['name' => 'casibom'],
            ['name' => 'ngsbahis'],
            ['name' => 'lordcasino'],
            ['name' => 'redwin'],
            ['name' => 'celtabet'],
            ['name' => 'kolaybet'],
            ['name' => 'dumanbet'],
            ['name' => 'restbet'],
            ['name' => 'bahsegel'],
            ['name' => 'perabet'],
            ['name' => 'tulipbet'],
            ['name' => 'makrobet'],
            ['name' => 'betpas'],
            ['name' => 'trbet'],
            ['name' => 'mrcasino'],
            ['name' => 'gencobahis'],
            ['name' => 'safirbet'],
            ['name' => 'savoybetting'],
            ['name' => 'nerobet'],
            ['name' => 'nero'],
            ['name' => 'goldenbahis'],
            ['name' => 'retrobet'],
            ['name' => 'gorabet'],
            ['name' => 'istanbulbahis'],
            ['name' => 'trendbet'],
            ['name' => 'routebet'],
            ['name' => 'bahisnow'],
            ['name' => 'astekbet'],
            ['name' => 'hiltonbet'],
            ['name' => 'aresbet'],
            ['name' => 'betgaranti'],
            ['name' => 'freybet'],
            ['name' => 'saraycasino'],
            ['name' => 'ofansifbet'],
            ['name' => 'betpipo'],
            ['name' => 'bahsine'],
            ['name' => 'lordbet'],
            ['name' => 'baysansli'],
            ['name' => 'ultrabet'],
            ['name' => 'betkanyon'],
            ['name' => 'casinometropol'],
            ['name' => 'betnbet'],
            ['name' => 'casinomaxi'],
            ['name' => 'favorisen'],
            ['name' => 'modabet'],
            ['name' => 'tempobet'],
            ['name' => 'ikimisli'],
            ['name' => 'slotbar'],
            ['name' => 'lolobet'],
            ['name' => 'casinolevant'],
            ['name' => 'adiosbet'],
            ['name' => 'timebet'],
            ['name' => 'simdibahis'],
            ['name' => 'kralbet'],
            ['name' => 'showbahis'],
            ['name' => 'betkent'],
            ['name' => 'betkoz'],
            ['name' => 'julibet'],
            ['name' => 'kalebet'],
            ['name' => 'betbaba'],
            ['name' => 'sultanbet'],
            ['name' => '22bet'],
            ['name' => 'klasbet'],
            ['name' => 'sportsbet'],
            ['name' => '1xbit'],
            ['name' => 'fashionbet'],
            ['name' => 'wonodd'],
            ['name' => 'betdoksan'],
            ['name' => 'padisahbet'],
            ['name' => 'galabet'],
            ['name' => 'romabet'],
            ['name' => 'betsidney'],
            ['name' => 'betasus'],
            ['name' => 'vippark'],
            ['name' => 'betsdot'],
            ['name' => 'galaxybetting'],
            ['name' => 'capitolbet'],
            ['name' => 'enobahis'],
            ['name' => 'nisanbet'],
            ['name' => 'grandpashabet'],
            ['name' => 'coinplaystar'],
            ['name' => 'setrabet'],
            ['name' => 'betkolik'],
            ['name' => 'atlantisbahis'],
            ['name' => 'hilabet'],
            ['name' => 'golegol'],
            ['name' => 'dolibet'],
            ['name' => 'casinoper'],
            ['name' => 'betmoy'],
            ['name' => 'betkur'],
            ['name' => 'betovis'],
            ['name' => 'vipbahis'],
            ['name' => 'betlesene'],
            ['name' => 'albibet'],
            ['name' => 'maltbahis'],
            ['name' => 'jupiterbahis'],
            ['name' => 'oynabet'],
            ['name' => 'bahislion'],
            ['name' => 'megabahis'],
            ['name' => 'bahisbudur'],
            ['name' => 'lizbonbet'],
            ['name' => 'betonbet'],
            ['name' => 'betandyou'],
            ['name' => 'sporcasino'],
            ['name' => 'jokerbet'],
            ['name' => 'altincasino'],
            ['name' => 'akcebet'],
            ['name' => 'atlasbet'],
            ['name' => 'winxbet'],
            ['name' => 'milosbet'],
            ['name' => 'bahisturk'],
            ['name' => 'kareasbet'],
            ['name' => 'sinyorbet'],
            ['name' => 'kazansana'],
            ['name' => 'kavbet'],
            ['name' => 'holiganbet'],
            ['name' => 'betorder'],
            ['name' => 'wolbet'],
            ['name' => 'lunabit'],
            ['name' => 'jestbahis'],
            ['name' => 'artemisbet'],
            ['name' => 'lidyabet'],
            ['name' => 'betadonis'],

          ];

          BetCompany::insert($betcompanies);
    }
}
